### ISSUE TITLE
Enable jar classes

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/app-gradle-plugin#100]
Hi,
when I deploy my project I get the following information:
```
INFORMATION: We detected that you have a large number of .class files in WEB-INF/classes. 
You may be able to reduce request latency by packaging your .class files into jars. 
To do this, supply the --enable_jar_classes flag when using appcfg on command line. 
If you're using the gcloud-maven-plugin, add <enable_jar_classes>true</enable_jar_classes> 
in the plugin's <configuration> tag. If you are using the appengine-maven-plugin, 
supply <enableJarClasses>true</enableJarClasses> in the plugin's <configuration> tag. 
Note that this flag will put the jar in WEB-INF/lib rather than WEB-INF/classes. 
The classloader first looks in WEB-INF/classes and then WEB-INF/lib when loading a class. 
As a result, this flag could change classloading order, which may affect the behavior of your app.
```
I think the option described for maven enableJarClasses is currently not available for this plugin?

**Comment by patflynn** [comment]
We have this parameter scoped to 'stage.'
```
     <stage.enableJarClasses>false</stage.enableJarClasses>
```

On Fri, Feb 10, 2017 at 5:08 PM, Frederik Bertling <notifications@github.com

**Comment by Burtan** [comment]
This is the config vor the maven plugin?

**Comment by patflynn** [comment]
aha. That is a good point. 

```
stage {
   enableJarClasses = true
}
```

**Comment by loosebazooka** [comment]
Also you can run 
```
./gradlew appengineShowConfiguration
``` 
to see all available parameters that can be configured in the appengine configuration closure in your build.gradle

**Comment by Burtan** [comment]
Ah thanks. I added it, but the information is still shown.

**Comment by loosebazooka** [comment]
Interesting, there might be a bug here, I'll take a look.

**Comment by loosebazooka** [comment]
@Burtan I believe this is fixed in the latest appengine tools in the Cloud SDK. Please re-open if you still see it after updating.
```
gcloud components update
```

**Comment by washowasho** [comment]
@loosebazooka , I have the latest update and still get this message.

**Comment by Burtan** [comment]
You need the lastest **Cloud SDK**, not just the latest plugin version

**Comment by washowasho** [comment]
What am I missing?

![image](https://cloud.githubusercontent.com/assets/6689967/25029813/b3b0c462-208e-11e7-844c-3105e16546f6.png)

**Comment by patflynn** [comment]
@loosebazooka

**Comment by loosebazooka** [comment]
Just to clarify, have you specified the enableJarClasses flag?
