### ISSUE TITLE
Plugin fails when using deep project structure

### ISSUE THREAD

**Issue by swftvsn** [GoogleCloudPlatform/app-gradle-plugin#108]
I have a project that has layout like this:

```
 - root
   | - ios
   | - android
   | - handler (in google cloud)
   | - trigger (in google cloud)
   | - etc..
```
When I run `./gradlew handler:appengineStage` from the root directory, staging fails with exception 
> Directory '[removed]/root/src/main/appengine' specified for property 'stagingConfig.appEngineDirectory' does not exist.

With plugin version 1.0 this used to work, but not anymore with 1.1. Should I have one appengine directory in the root folder and then separate appengine folders in handler and trigger folders?

All the projects are deployed to the same Google Cloud project, but represent different Services, so the cron.yaml should go to root/src/main/appengine, but the app.yaml files to project specific appengine folders? Is this correct? I have src/main/appengine folder in all projects that are destined to be deployed to Google Cloud, but not in the root project.

**Comment by loosebazooka** [comment]
Have you modified any of the default configuration? It's hard to guess what's going on here. Ideally if you're deploying cron.yaml/index.yaml outside of an appengine module, you might as well just use 
```
gcloud app deploy cron.yaml
```
as the plugin isn't adding any value. However if there is a compelling case for this helping out workflow, perhaps we can incorporate that into our future design.

**Comment by patflynn** [comment]
@loosebazooka what about the staging issue?

**Comment by swftvsn** [comment]
Yeah, but the deployment fails completely, as it tries to find the appengine directory from the root/src/main/appengine instead of the subproject I'm trying to deploy, that contains the correct app.yaml. My root directory does not contain _any_ code, only master build.gradle, there is no src directory.

I haven't tried with an empty appengine directory in root though. (Quite usually I don't want to deploy all services at the same time, so I just execute `./gradlew subproject:appengineDeploy`, but as said, this fails as it's expecting appengine directory in the root folder, which does not exists.

**Comment by loosebazooka** [comment]
okay thanks, I'll try to reproduce.

**Comment by swftvsn** [comment]
Maybe the error is because my master gradle file does not have anything related to this plugin, the subprojects have separate configurations for the cloud deployment?

**Comment by loosebazooka** [comment]
So, I can't reproduce, my directory structure and plugins
root - (with no appengine-gradle-plugin)
 - appengine-module1 (with: appengine-gradle-plugin)
 - appengine-module2 (with: appengine-gradle-plugin)

**Comment by loosebazooka** [comment]
Are you applying the plugin in the master buildfile? Simliar to how the android plugin is applied?

**Comment by swftvsn** [comment]
No, I'm applying the plugin in child projects.

**Comment by loosebazooka** [comment]
Oh this is a flex application. maybe project.getRootDir() isn't doing what I think it should be doing and we're setting the wrong defaults when running from root for the appengine project. Lemme take a look. In the meantime can you run

```
./gradlew :handler:appengineShowConfiguration
```
to see what the defaults are being set to for (stage.appEngineDirectory and stage.dockerDirectory)

**Comment by loosebazooka** [comment]
Okay, so I think I can confirm this is a bug for flex deployments, I'll post a fix and an update soon. Thanks for reporting.

In the meantime you can explicitly override that parameter in your buildfile for handler to be the correct location
```
appengine {
  ...
  stage {
     appEngineDirectory = "${project.projectDir}/src/main/appengine"
  }
  ...
}
```

**Comment by loosebazooka** [comment]
So this should be fixed with 1.1.1 which should post to mavenCentral today

**Comment by swftvsn** [comment]
Absolutely awesome! Confirmed to work. Thanks for the quick turn around @loosebazooka, @patflynn and the rest of the team!

**Comment by patflynn** [comment]
@swftvsn thank you for filing the bug! Keep them coming.
