### ISSUE TITLE
<static-error-handlers> does not work with local dev environment

### ISSUE THREAD

**Issue by icoloma** [GoogleCloudPlatform/app-gradle-plugin#115]
Something is wrong with how static files are processed in `yaml_translator.py`.

The symptom: when using a custom error handler in `appengine-web.xml`: 

```xml
  <static-files>
    <include path="/error/**"/>
  </static-files>

  <static-error-handlers>
    <handler file="/error/default.html" error-code="default"/>
    <handler file="/error/over_quota.html" error-code="over_quota"/>
    <handler file="/error/dos_api_denial.html" error-code="dos_api_denial"/>
    <handler file="/error/timeout.html" error-code="timeout"/>
  </static-error-handlers>
```

Either  `dev_appserver.py src/main/webapp/` or `gradle appengineRun` will fail with the error:

```
google.appengine.tools.app_engine_config_exception.AppEngineConfigException: No static file found for error handler: error/default.html, out of []
```

The files exist. By looking at `yaml_translator.py`, it seems that there are two variables being used for mostly the same:

* `self.static_urls` is initialized in `yaml_translator.py` by comparing the contents of the `static-files` section of `appengine-web.xml` with the contents of (in this case) `src/main/webapp`. This is correct.
* `self.static_files` is initialized in `appcfg_java.py#_GetStaticFileList()`, which basically just searches for files in the `__static__` folder. This does not seem correct, and in this case this list is empty.

The problem seems to be that `yaml_translator.py#ErrorHandlerPath()` is comparing the `static-error-handler` entry with `self.static_files`, which is always empty. 

gradle plugin version: 1.1.1
SDK is included in gcloud install (app-engine-java 1.9.50, app-engine-python 1.9.50)
python version 2.7.12
Java version 1.7.0_80

**Comment by patflynn** [comment]
@icoloma thanks for the detailed report.

@loosebazooka can we verify that this is working with the new updates? It also sounds like we need to file a bug with devappserver2.

**Comment by loosebazooka** [comment]
@davidjn

**Comment by loosebazooka** [comment]
@davidjn FYI

**Comment by loosebazooka** [comment]
@icoloma, we've exposed dev appserver 1 as the default in plugin version 1.3.0-rc1 and going forward until dev appserver 2 is brought up to speed for java.

Can you try running your application with 1.3.0-rc1 to see if the issue persists?

**Comment by TadCordle** [comment]
Closing stale issue; feel free to reopen if this is still a problem.
