### ISSUE TITLE
When starting local dev server, the server does not create datastore

### ISSUE THREAD

**Issue by mangan77** [GoogleCloudPlatform/app-gradle-plugin#124]
Hi,

When I use the plugin to start my local dev server, the server does not create a datastore when needed. Calls to the datastore will throw exception with message: 

> remote API call: I/O error

 

If I use `appengine-java-sdk/bin/dev_appserver.sh` this works just fine. 

Am I missing something in my setup of App Engine or in the configuration of the plugin?
Can I get the plugin to run the `appengine-java-sdk` instead?

Right now this prevents me from using the plugin, which is unfortunate.

**Comment by patflynn** [comment]
Hi @mangan77.  which version of the library are you on? If it's not 1.3.0 could you try that version to see if it fixes your problem?

**Comment by mangan77** [comment]
My bad. 

Kinda thought the latest version was the one in the README, but that was not the case. Switched version to 1.3.0 and everything works great!

Thanks @patflynn !

**Comment by patflynn** [comment]
@mangan77 no prob!  We just did the release and the documentation will be updated shortly.
