### ISSUE TITLE
Unable to upload java8 standard environment

### ISSUE THREAD

**Issue by halldors** [GoogleCloudPlatform/app-gradle-plugin#134]
Hi get an error when trying to upload a simple demo Spring Boot application.
The exact same application works fine with com.google.appengine:gradle-appengine-plugin:1.9.53

I'm using a mac, with news gcloud sdk and appengine sdk. 

The error is.
:appengineStage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':appengineStage'.
> Directory '/Users/halldor/Development/demojava/src/main/appengine' specified for property 'stagingConfig.appEngineDirectory' does not exist.

**Comment by loosebazooka** [comment]
Where is your appengine-web.xml in your project structure?

**Comment by halldors** [comment]
its in src/main/webapp/WEB-INF/

**Comment by patflynn** [comment]
@halldors 
Do you have a link to the demo spring boot app that you used?

**Comment by halldors** [comment]
Just upload it.
https://github.com/halldors/springhelloworld

**Comment by loosebazooka** [comment]
Thanks for uploading it, there's two things going on here.
1. Our auto detection uses the war plugin to find the appengine-web.xml, so in general we expect that to be  applied before the appengine plugin (although hopefully users can just bypass autodetection with #132)
2. There is a bug in our fallback mechanism that tries to find the appengine-web.xml in the default location (#136)

So I'll fix `2` and publish #132 and they will go out in a future release, but in the meantime you can move `apply plugin: 'war'` above `apply plugin: 'com.google.cloud.tools.appengine'` in your `build.gradle` and you should be good to go.

**Comment by halldors** [comment]
@loosebazooka Thanks, that worked.

**Comment by patflynn** [comment]
@Appu this ordering of plugins is going to catch some people out.  Can we
call this out in our docs?

Is there any mitigation we can do in code?

**Comment by loosebazooka** [comment]
@patflynn that's what the fallback was supposed to help with, but it was misconfigured #136. Can add to docs though.
