### ISSUE TITLE
appengineRun needs to depend on appengineStage

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/app-gradle-plugin#149]
App source:
https://github.com/GoogleCloudPlatform/getting-started-java/tree/638a44e/appengine-standard-java8/helloworld

To reproduce, run:
```
./gradlew clean appengineRun
```

Output:
```
$ ./gradlew clean appengineRun
:clean
:compileJava
:processResources NO-SOURCE
:classes
:war
:explodeWar
:assemble
:appengineRun
Jun 13, 2017 6:02:17 PM com.google.apphosting.utils.config.AbstractConfigXmlReader readConfigXml
SEVERE: Received exception processing /usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/getting-started-java/appengine-standard-java8/helloworld/build/exploded-helloworld_java8_GAE_standard/WEB-INF/web.xml
com.google.apphosting.utils.config.AppEngineConfigException: Could not locate /usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/getting-started-java/appengine-standard-java8/helloworld/build/exploded-helloworld_java8_GAE_standard/WEB-INF/web.xml

<snip>
```

I can tell you what versions of everything I'm using if you give me the appropriate commands to find out (sorry, Gradle noob).

**Comment by loosebazooka** [comment]
Appengine run uses the exploded app directory, not the staged directory. So
this is working as intended.

**Comment by broady** [comment]
I don't know what that means. All I know is that `./gradlew appengineRun` doesn't work on an unbuilt project.

**Comment by broady** [comment]
web.xml is generated during staging.

**Comment by loosebazooka** [comment]
We do not run the dev-appserver from a directory created by staging. The dev appserver from the java SDK doesn't even understand the directory structure from a staged-output directory.

It looks like what we want here is for the dev appserver to handle this correctly (no web.xml, maybe there's some java8 flag @ludoch) or for conversion to run before creating a war.

**Comment by loosebazooka** [comment]
are your gcloud components up to date?

```
gcloud components update
```

**Comment by lesv** [comment]
@broady You might wish to share your project w/ @loosebazooka (Appu).  We saw that things weren't working w/ `gradle clean appengineRun`

**Comment by loosebazooka** [comment]
Closing this for now, if you have an update, please reopen.
