### ISSUE TITLE
services/pubsub: setup topic & subscription on deployment

### ISSUE THREAD

**Issue by mgenov** [GoogleCloudPlatform/app-gradle-plugin#155]
The thing that bothers me for pub/sub usage on standard environment is that there is no automatic way for update of topics and subscriptions on deployment.

Here is an init servlet that updates topic and subscriptions but it requires a remote client to call it.
https://github.com/GoogleCloudPlatform/cloud-pubsub-samples-java/blob/master/appengine-push/src/main/java/com/google/cloud/pubsub/client/demos/appengine/servlet/InitServlet.java

I though that google-appengine-plugin/app-gradle-plugin could deal with this stuff as it is authenticated and is able to use the pubsub api. What you guys think about this topic ?

**Comment by loosebazooka** [comment]
We haven't really explored this area much, @patflynn does the pub-sub team have a recommended approach for this?

**Comment by patflynn** [comment]
Hi @mgenov! 

Thanks for your feedback.

Unfortunately I don't understand the question. appengine and pubsub are separate services, and the app-gradle-plugin is designed purely for app engine deployments. What exactly would you want automated?

**Comment by mgenov** [comment]
Hi @patflynn!

I will try to explain what I mean. Lets say that we have 2 GAE services: publisher and subscriber. To be able to use pubsub it's required topic to be created for the publisher and subscription for the subscriber service.

Currently this could be done from some kind of [InitServlet](https://github.com/GoogleCloudPlatform/cloud-pubsub-samples-java/blob/master/appengine-push/src/main/java/com/google/cloud/pubsub/client/demos/appengine/servlet/InitServlet.java) like shown in the example. The problem of the InitServlet is that it will not be invoked automatically, e.g someone has to call it to ensure that subscriptions and topic are created. Init call of Servlet could be used also but it requires boot request to be send to the application. 

I hope that this cleans things up.

**Comment by patflynn** [comment]
would you be ok with using the [cloud console UI](https://console.cloud.google.com/cloudpubsub) to create them before hand? 

Another option is to use the beta gcloud pubsub command to create the topic before you deploy:
`gcloud beta pubsub topics create my-test-topic`

**Comment by mgenov** [comment]
Yeah I knew about cloud console UI and gcloud commands as I've already used it for testing purposes.

A go/java tool could be created also that is using the REST API or grpc for dealing with the configuration of pubsub directly but it's adds additional tool in our toolchain which I was trying to skip by suggesting feature to be added in the gradle plugin for GAE. 

Thanks for your feedback @patflynn

**Comment by patflynn** [comment]
I see.  So the feature request is to have a means of creating pubsub queues
at the time your app engine app is deployed?

**Comment by mgenov** [comment]
Yeah, it will ensure that pubsub topics and subscriptions which are required for the deployed service are up and ready.

**Comment by patflynn** [comment]
@ludoch 
@saturnism 

any thoughts on this?

**Comment by ihommani** [comment]
Hi, any news on this topic?

**Comment by patflynn** [comment]
No plans to implement this on our side.

I recommend using your own groovy command to call the gcloud CLI.
