### ISSUE TITLE
deploy to different projects

### ISSUE THREAD

**Issue by sh4d0000** [GoogleCloudPlatform/app-gradle-plugin#157]
I have different google app engine project per environment, let's say myproj-staging and myproj-prod.
Currently I suppose the plugin is using gcloud to decide the app id. It would be nice to have an option on the appengineDeploy task to override that value.

**Comment by sh4d0000** [comment]
Sorry, this is already possible using the 'project' property on the appengineDeploy task

**Comment by loosebazooka** [comment]
Right which would be the explicit way to specify it.
