### ISSUE TITLE
java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/NashornScriptEngineFactory when running locally

### ISSUE THREAD

**Issue by vh** [GoogleCloudPlatform/app-gradle-plugin#160]
Catching this exception in a project which uses Nashorn when trying to run `gradle appengineRun`. 
But deployed version works fine!

**Comment by patflynn** [comment]
Hi @vh!

Which java runtime are you using? Default or <runtime>java8</runtime>

**Comment by vh** [comment]
Hi @patflynn!

java8

**Comment by loosebazooka** [comment]
How are you including the nashorn dependencies?

**Comment by vh** [comment]
Hi @loosebazooka!
Nohow. This is part of JDK 8.

**Comment by loosebazooka** [comment]
Oops. Okay, maybe @ludoch knows then.

**Comment by patflynn** [comment]
Could it be that the wrong JDK is being used for the local run?

**Comment by vh** [comment]
@patflynn 1.8.0_144
```
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

**Comment by vh** [comment]
IntelliJ Idea (+ Google Cloud Tools) shows the same exception.
It seems bug somewhere in `com.google.cloud.tools:appengine-plugins-core`. Such dep is also used by intellij plugin.

**Comment by ludoch** [comment]
It works with the original GAE maven plugin, that is all I can say.

**Comment by loosebazooka** [comment]
@vh any chance you can send us a minimized app so we can analyze this?

**Comment by vh** [comment]
@ludoch just checked with
```
<plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>1.3.1</version>
</plugin>
```
no, it doesn't

**Comment by loosebazooka** [comment]
I believe ludo is referring to

```
<plugin>
    <groupId>com.google.appengine</groupId>
    <artifactId>appengine-maven-plugin</artifactId>
    <version>1.9.54</version>
</plugin>
```

**Comment by patflynn** [comment]
I can reproduce with a helloworld application in both
com.google.cloud.tools app-maven-plugin and com.google.appengine
appengine-maven-plugin.

**Comment by patflynn** [comment]
@ludoch How did you test this?

**Comment by patflynn** [comment]
FYI I'm on OS X.

**Comment by vh** [comment]
@loosebazooka checked `<groupId>com.google.appengine</groupId>` maven plugin - exception appears. I've created test example to reproduce such bug https://github.com/vh/appengine-nashorn

I'm also on OS X

**Comment by loosebazooka** [comment]
@vh thanks for the update.

**Comment by ludoch** [comment]
Was using this code line that is working:

      ScriptEngine engine = new
ScriptEngineManager(null).getEngineByName("nashorn");

**Comment by loosebazooka** [comment]
@vh thanks for the minimized project : https://github.com/vh/appengine-nashorn I seem to be able to recreate this with the old and new plugins.

**Comment by loosebazooka** [comment]
@vh, using
```
ScriptEngine engine = new ScriptEngineManager(null).getEngineByName("nashorn");
```
instead of 
```
      engine = (NashornScriptEngine)new NashornScriptEngineFactory().getScriptEngine();
```
seems to make it work. I'm not sure familiar with ScriptEngines, but could that be it?

**Comment by vh** [comment]
@loosebazooka aha, such workaround works! I've modified example a little, because in my case it is necessary to initialize scripting engine with args this way `new NashornScriptEngineFactory().getScriptEngine("-strict", "--language=es6")`. And it seems it is not possible to do that using `ScriptEngineManager`.

**Comment by loosebazooka** [comment]
@ludoch any ideas?

**Comment by loosebazooka** [comment]
@vh if you're still seeing this, can you file this bug against the appengine bug tracker so they can track it : https://issuetracker.google.com/issues?q=componentid:187191

**Comment by vh** [comment]
@loosebazooka Yes. I've found that it is problem with local dev classloader. Not gradle plugin issue. Thanks for help!

**Comment by mpoehler** [comment]
@vh Is that already fixed? I probably ran into this again here: https://github.com/jknack/handlebars.java/issues/652 

`new ScriptEngineManager().getEngineByName("nashorn");`

returns `null` in local devserver, but works in tests and also in production.

I created a dedicated repo for that issue here: https://github.com/mpoehler/hbs-test

Can you give me a hint regarding the classloading issue in the devserver?
