### ISSUE TITLE
Add minimum gradle version check

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-gradle-plugin#169]
Something like this : https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/blob/master/src/main/groovy/com/google/appengine/AppEnginePlugin.groovy#L176

since we use features in newer versions of gradle (like Sync)

Issues popping up : https://groups.google.com/forum/#!topic/google-appengine/TSglEs0voO8

**Comment by coollog** [comment]
What should be our new minimum Gradle version?

**Comment by loosebazooka** [comment]
I think sync is in 3.3, but we should set it to 4.0 because that's what our docs say : https://github.com/GoogleCloudPlatform/app-gradle-plugin#requirements

**Comment by coollog** [comment]
The gradle wrapper is currently version 3.4.1 - should I update that too then?

**Comment by loosebazooka** [comment]
hrmm... maybe just change the documentation instead to 3.4.1?

**Comment by loosebazooka** [comment]
set minimum version to 3.4.1, the lower the better, right?

**Comment by coollog** [comment]
Okay, sounds good.

**Comment by coollog** [comment]
Looks like the user can also directly use the `standard` or `flexible` plugins (ie. `com.google.cloud.tools.appengine-flexible`), and it skips over this check. I'll have to make this check work for these too.

**Comment by loosebazooka** [comment]
good call.

**Comment by loosebazooka** [comment]
You can put it in https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/src/main/java/com/google/cloud/tools/gradle/appengine/core/AppEngineCorePlugin.java too.
