### ISSUE TITLE
Publish to Gradle Plugin Portal

### ISSUE THREAD

**Issue by int128** [GoogleCloudPlatform/app-gradle-plugin#173]
Is there any chance publishing to [Gradle Plugin Portal](https://plugins.gradle.org/)? Developers can use this plugin by only following line, instead of `buildscript` block.

```groovy
plugins {
  id 'com.google.cloud.tools.appengine' version '1.3.3'
}
```

Also buildscript will be easy. [gradle-plugin-starter project](https://github.com/int128/gradle-plugin-starter) is good starting point. I am happy to help.

**Comment by loosebazooka** [comment]
I would love to, unfortunately, the gradle plugin portal doesn't provide download statistics and we can't support their repository until they do. See : https://discuss.gradle.org/t/plugin-portal-download-statistics/11609

**Comment by int128** [comment]
Thank you for the quick reply. I got it.
