### ISSUE TITLE
appengine-web.xml env-variables exposed in development server

### ISSUE THREAD

**Issue by marceloverdijk** [GoogleCloudPlatform/app-gradle-plugin#195]
When e.g. having

```
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">

    <runtime>java8</runtime>
    <threadsafe>true</threadsafe>

    <env-variables>
        <env-var name="SPRING_PROFILES_ACTIVE" value="prod" />
    </env-variables>

</appengine-web-app>
```

the `SPRING_PROFILES_ACTIVE` is exposed in the local development server.

However in https://cloud.google.com/appengine/docs/standard/java/config/appref it is stated that:

> To avoid conflicts with your local environment, the development server does not set environment variables based on this file, and requires that the local environment have these variables already set to matching values.
> 
> export DEFAULT_ENCODING="UTF-8"
> dev_appserver war

I'm not sure if this a issue with the Gradle plugin or the devserver itself.

**Comment by loosebazooka** [comment]
Oh yeah these plugins do special handling to standardize the behavior between two different versions of the dev appserver. However, the dev appserver implementation itself will not allow you to overwrite this value with values from your plugin.

for instance you cannot do
```
appengine {
  run {
    env = SPRING_PROFILES_ACTIVE: "test"
  }
}
```

I think you have to do some resource filtering to write in a value into appengine-web.xml

@patflynn, @etanshaul ?

**Comment by marceloverdijk** [comment]
Yes indeed, that's what I'm looking at now (resource filtering).
As it is a Spring Boot application I think it's even easier to resource filtering on my application.yml which also contains the active profile.

**Comment by marceloverdijk** [comment]
Note something like this works:

```
spring:
  profiles.active: ${System.properties['spring.profiles.active'] ?: 'dev'}
```

but the problem is when running code (e.g. directly from IDE) which does not run the `processResources` task then this won't work.
So thinking about it again, probably it's better to replace the value in `appengine-web.xml` after all.

Resource filtering (or in Gradle terms `expand`) works for resource files but for files in the webapp folder. I tried adding something like:

```
tasks {
    "war"(War::class) {
        filesMatching("appengine-web.xml") {
            expand(project.properties)
        }
    }
}
```
but it didn't work when executing `appengineRun`.
What I basically need is a Gralde configuration to do resource filtering when executing `appengineRun` or `appengineDeploy`.
If somebody has an idea how to do that I would be happy to hear it.

**Comment by marceloverdijk** [comment]
Just for reference, for now I'm going for this in Spring Boot's `application.yml`:

```
spring:
  profiles.active: ${System.properties['spring.profiles.active'] ?: 'dev'}
```

Which is replaced using Gradle's expand:

```
tasks {
    "processResources"(ProcessResources::class) {
        filesMatching("application.yml") {
            expand(project.properties)
        }
    }
}
```

**Comment by marceloverdijk** [comment]
I need to reconsider this. Using resource filtering / expand strongly ties the build to the active profiles used.

Is there no other way to pass a system property or env variable to the hosted AppEngine Standard environment, but that is not available in de local dev server?

**Comment by vijayakumar-psg587** [comment]
I am also trying to pass in the active profile of spring but by using maven. I tried with setting the env variable in `appengine-web.xml`. Here it is

```
<env-variables>
		<env-var name="spring.profiles.active" value="QA" />
	</env-variables>
```
I deployed it using `mvn -X clean package appengine:deploy` and this is the error that I end up with.

[

> INFO] GCLOUD: 2018-10-29 23:27:16.973:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=1151ms
> [INFO] GCLOUD: 2018-10-29 23:27:16.987:INFO:oejq.QuickStartDescriptorGenerator:main: Quickstart generating
> [INFO] GCLOUD: 2018-10-29 23:27:16.998:INFO:oejsh.ContextHandler:main: Started o.e.j.q.QuickStartWebApp@4883b407{/,[file:///Users/vijayakumar_psg587/githublocal/adtechservices/target/appengine-staging/, jar:file:///Users/vijayakumar_psg587/githublocal/adtechservices/target/appengine-staging/WEB-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],AVAILABLE}
> [INFO] GCLOUD: 2018-10-29 23:27:17.001:INFO:oejs.Server:main: Started @1897ms
> [INFO] GCLOUD: 2018-10-29 23:27:17.004:INFO:oejsh.ContextHandler:main: Stopped o.e.j.q.QuickStartWebApp@4883b407{/,file:///Users/vijayakumar_psg587/githublocal/adtechservices/target/appengine-staging/,UNAVAILABLE}
> [INFO] GCLOUD: 0% Generated git repository information file.
> [INFO] GCLOUD: Success.
> [INFO] GCLOUD: Temporary staging for module adtech-service-dev directory left in /Users/vijayakumar_psg587/githublocal/adtechservices/target/appengine-staging
> Oct 29, 2018 11:27:17 PM com.google.cloud.tools.appengine.cloudsdk.GcloudRunner run
> INFO: submitting command: /Users/vijayakumar_psg587/Library/Application Support/google-cloud-tools-java/managed-cloud-sdk/220.0.0/google-cloud-sdk/bin/gcloud app deploy --version v04 --project sample-project-vijay
> [INFO] GCLOUD: ERROR: (gcloud.app.deploy) An error occurred while parsing file: [/Users/vijayakumar_psg587/githublocal/adtechservices/target/appengine-staging/app.yaml]
> [INFO] GCLOUD: Value 'spring.profiles.active' for key in EnvironmentVariables does not match expression '^(?:[a-zA-Z_][a-zA-Z0-9_]*)$'
> [INFO] GCLOUD:   in "/Users/vijayakumar_psg587/githublocal/adtechservices/target/appengine-staging/app.yaml", line 10, column 29
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 18.733 s
> [INFO] Finished at: 2018-10-29T23:27:18+05:30
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.0.0-rc2:deploy (default-cli) on project AdTechServices: Standard application deployment failed: com.google.cloud.tools.appengine.cloudsdk.process.ProcessHandlerException: com.google.cloud.tools.appengine.api.AppEngineException: Non zero exit: 1 -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.0.0-rc2:deploy (default-cli) on project AdTechServices: Standard application deployment failed
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:498)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoExecutionException: Standard application deployment failed
>     at com.google.cloud.tools.maven.AppEngineStandardDeployer.deploy (AppEngineStandardDeployer.java:52)
>     at com.google.cloud.tools.maven.DeployMojo.execute (DeployMojo.java:29)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:498)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
> Caused by: com.google.cloud.tools.appengine.api.AppEngineException: com.google.cloud.tools.appengine.cloudsdk.process.ProcessHandlerException: com.google.cloud.tools.appengine.api.AppEngineException: Non zero exit: 1
>     at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDeployment.deploy (CloudSdkAppEngineDeployment.java:90)
>     at com.google.cloud.tools.maven.AppEngineStandardDeployer.deploy (AppEngineStandardDeployer.java:50)
>     at com.google.cloud.tools.maven.DeployMojo.execute (DeployMojo.java:29)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:498)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)


I tried it with passing the env variable with -PQA like 

> mvn -X clean package appengine:deploy -PQA 

but the profile is not set
