### ISSUE TITLE
Need a sample project showing how to use getExplodedAppDir

### ISSUE THREAD

**Issue by JohannBlake** [GoogleCloudPlatform/app-gradle-plugin#198]
I have spent the greater part of the day trying to use the plugin for multiple modules but have been unsuccessful. I would like to debug my app locally. I need an actual project that shows 2 or more modules along with the build.gradle files to show how to set this up.

I am not a gradle expert but have done enough of it with Android to know my way around. Still, this plugin has been very hard to implement.

**Comment by loosebazooka** [comment]
Lets see if we can get you going with this:

If you have 2 modules in your project
- module1 (with com.google.cloud.tools.appengine-gradle-plugin)
- module2 (with com.google.cloud.tools.appengine-gradle-plugin)

you would add this code to module1/build.gradle and run `./gradlew :module1:appengineRun`

```
appengine {
  run {
    // configure the app to point to the right service directories
    services = [
        getExplodedAppDir(project),
        getExplodedAppDir(project(":module2"))
    ]
  }
}

def getExplodedAppDir(Project p) {
  if (p != project) {
    evaluationDependsOn(p.path)
    project.tasks.appengineRun.dependsOn p.tasks.explodeWar
  }
  return p.tasks.explodeWar.explodedAppDirectory
}
```

If that doesn't work, please update with the error and we can work from there.

**Comment by JohannBlake** [comment]
Pat Flynn gave me a sample code. It's listed under the branch "cloud-sdk-refactor" and is located at:

[https://github.com/patflynn/appengine-potpourri/tree/cloud-sdk-refactor](https://github.com/patflynn/appengine-potpourri/tree/cloud-sdk-refactor)

This sample is the only one that apparently exists anywhere on Internet and even then it's buried in some branch on github. I downloaded and tried out the sample and it works. It would be very useful to other devs if you included a link to that sample at:

[https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/USER_GUIDE.md](https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/USER_GUIDE.md)

NOTE: The master branch for that sample does not have the code showing getExplodedAppDir.
