### ISSUE TITLE
appengine-web.xml migration to app.yaml

### ISSUE THREAD

**Issue by gmiller-in-situ** [GoogleCloudPlatform/app-gradle-plugin#202]
For GAE standard applications, it seems like we still need to use an appengine-web.xml to configure the service, while flexible services are supported with an app.yaml. Is there a reason for this? It makes it harder to run the standard services locally when I have to maintain a fake YAML file for dev_appserver.

**Comment by loosebazooka** [comment]
I'm not sure I understand your problem. There isn't a requirement to maintain an app.yaml for standard applications. Could you provide some more detail?

**Comment by gmiller-in-situ** [comment]
I'm developing a GAE app with multiple services, most of which are written in Python. This new service is being written with Java, and I'm trying to locally test them all alongside each other using dev_appserver.py. This requires me to create a fake YAML file for dev_appserver to pick up, and then it starts jetty. (This also doesn't quite seem to work right at the moment)

**Comment by loosebazooka** [comment]
I believe the devappserver included in the cloud sdk should pick up an exploded app directory. How are you running this multi-service application?

**Comment by gmiller-in-situ** [comment]
In a command line, I can run `gradle appengineStage` and then `dev_appserver.py build/exploded-public-api/` and it will start serving my static files, but does not seem to start my servlet properly (needs servlet 3.0 support for annotations)

**Comment by loosebazooka** [comment]
appengineStage creates a staged app for you in build/staged-app with a generated app.yaml

are you able to run `dev_appserver.py build/staged-app/app.yaml` ?

**Comment by gmiller-in-situ** [comment]
I can, and I get an output on the console like the following: 
`$ dev_appserver.py public-api/build/staged-app/app.yaml
INFO     2018-02-21 19:23:06,698 devappserver2.py:105] Skipping SDK update check.
INFO     2018-02-21 19:23:06,750 api_server.py:265] Starting API server at: http://localhost:50025
INFO     2018-02-21 19:23:06,761 dispatcher.py:255] Starting module "public-api" running at: http://localhost:8080
INFO     2018-02-21 19:23:06,763 admin_server.py:152] Starting admin server at: http://localhost:8000
WARNING  2018-02-21 19:23:06,763 devappserver2.py:177] No default module found. Ignoring.`

After making a request for a url I've mapped on the server, I get the following output:

`Feb 21, 2018 7:29:10 PM com.google.appengine.tools.development.AbstractContainerService configure
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
2018-02-21 19:29:10.451:INFO::main: Logging initialized @577ms
2018-02-21 19:29:10.747:INFO:oejs.Server:main: jetty-9.3.18.v20170406
2018-02-21 19:29:11.179:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=56ms
2018-02-21 19:29:11.434:INFO:oejsh.ContextHandler:main: Started c.g.a.t.d.j.DevAppEngineWebAppContext@7ce026d3{/,file:///Users/gmiller/workspace/skynet/public-api/build/staged-app/,AVAILABLE}{/Users/gmiller/workspace/skynet/public-api/build/staged-app}
2018-02-21 19:29:11.451:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@221a3fa4{HTTP/1.1,[http/1.1]}{localhost:50095}
2018-02-21 19:29:11.462:INFO:oejs.Server:main: Started @1588ms
Feb 21, 2018 7:29:11 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance public-api is running at http://localhost:50095/
Feb 21, 2018 7:29:11 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:50095/_ah/admin
Feb 21, 2018 7:29:11 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
INFO: Dev App Server is now running
Feb 21, 2018 7:29:11 PM com.google.appengine.tools.development.jetty9.LocalResourceFileServlet doGet
WARNING: No file found for: /public-api/docs/view
INFO     2018-02-21 19:29:11,801 module.py:835] public-api: "GET /public-api/docs/view HTTP/1.1" 404 83`

**Comment by loosebazooka** [comment]
Maybe you have to explicitly enable quickstart when creating the staged directory?

```
appengine {
  stage {
     enableQuickstart = true
  }
}
```

I'm just guessing here though, @ludoch do you know who might know what's going on here?

**Comment by gmiller-in-situ** [comment]
I just tried adding that configuration and rebuilding, and it did not change behavior. I thought that with spring boot I did not _need_ a web.xml, but perhaps I need to create one in order to tell dev_appserver.py how to start my app. This all works fine once deployed, btw.

**Comment by loosebazooka** [comment]
Oh it wasn't clear to me that you were using springboot. This is kind of outside the scope of what I'm familiar with. What guide were you following? https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard

Also does the module itself run fine when using ./gradlew appengineRun?

**Comment by gmiller-in-situ** [comment]
Yes, my project structure looks very similar to that demo, which is where I started from. The project runs fine on both bootRun and appengineRun, and it also runs fine if I point java_dev_appserver to it.

**Comment by loosebazooka** [comment]
So it only does not work fine when you run in with dev_appserver.py?

**Comment by gmiller-in-situ** [comment]
Yes.

**Comment by loosebazooka** [comment]
Okay, I'll try to reroute that team : @ludoch, @betamos, @cgwy any ideas?

**Comment by patflynn** [comment]
@davidjn

**Comment by gmiller-in-situ** [comment]
Update: steps to reproduce.
Clone https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard
Run mvn appengine:stage
Point dev_appserver.py to the appengine-staging directory produced by Maven

**Comment by cthrax** [comment]
@loosebazooka @patflynn @ludoch @betamos @cgwy @davidjn any thoughts on this? We've been limping along without being able to run locally, but it would be really nice to have a full system running locally. I know google cloud has had a ton of updates over the last year and a half, so i thought maybe there was a different solution here that didn't exist before?

**Comment by meltsufin** [comment]
Closing due to age and lack of activity. Please re-open if this is still relevant.
