### ISSUE TITLE
deploy should deploy app.yaml, index.yaml, cron.yaml, and dos.yaml

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-gradle-plugin#21]
Based off of the AppCfg code [here](https://code.google.com/p/googleappengine/source/browse/trunk/java/src/main/com/google/appengine/tools/admin/AppVersionUpload.java?r=182#152), I think we should deploy all of the above-mentioned configs at deploy time by default.

**Comment by loosebazooka** [comment]
we're not doing this anymore

**Comment by davidsantiago** [comment]
Can I ask what the thinking here is? It would seem helpful to me to have an appengine deployment tool manage all of the things that need to be done to deploy the app. The documentation still seems to suggest that having these files in WEB-INF is sufficient to deploy them, and the other appengine plugin appears to do this. I'm sure the reasoning is sound, I'm just not understanding it.

**Comment by patflynn** [comment]
@davidsantiago 
@markpell (for fact checking)

Hi David,  this is part of the standardizing of App Engine infrastructure across languages and onto the same SDK (gcloud).  In the new model we're going to be asking our Java users to use yaml files as the source of truth for all the non appengine-web.xml configuration files.  You'll be able to store them wherever you like and deploy them directly with gcloud using, for instance, `gcloud app deploy index.yaml`.  In addition you can add the files explicitly to your appengine-gradle-plugin deployables to deploy them with your app.  The only caveat being that there are no transactionality guarantees in those combined deployments (gcloud simply runs them serially).  Datastore indexes for instance take some time to build and you would normally need to push the index and wait for it to complete before you deployed your app.  We hope the new model and updated docs will make that more clear to our users. 

We're unfortunately in transition with our gradle tooling without clear documentation on how to use the new stuff. We are working on fixing that and should have updated docs very soon.

**Comment by davidsantiago** [comment]
Thank you. As I said, I knew there had to be a good reason. I look forward to the improved documentation, because your explanation here just helped me understand how the deployment process works in general. I had not expected the indexes to be instantaneous to update, but I thought there would be a wait on them before the version updated, or something similar.
