### ISSUE TITLE
Replacement for  GWT AppEngineLauncher

### ISSUE THREAD

**Issue by akbertram** [GoogleCloudPlatform/app-gradle-plugin#229]
I would like to upgrade to this plugin, but I am missing a replacement for the class com.google.appengine.tools.development.gwt.AppEngineLauncher which we currently use to run the AppEngine development server together with GWT's code server.

Is there a migration path available or planned, or would I need to provide my own implementation of ServletContainerLauncher using the appengine-plugins-core library?

**Comment by loosebazooka** [comment]
I'm not actually sure what you mean. Can you explain how you were using AppEngineLauncher before?

**Comment by akbertram** [comment]
The [AppEngineLauncher](https://cloud.google.com/appengine/docs/standard/java/tools/javadoc/com/google/appengine/tools/development/gwt/AppEngineLauncher) class is part of the SDK, and implements GWT's [ServletContainer](http://www.gwtproject.org/javadoc/latest/com/google/gwt/core/ext/ServletContainer.html) interface. 

My gradle file includes the following:
```

task appengineDevMode(type: JavaExec) {
    dependsOn appengineDownloadSdk
    dependsOn appengineExplodeDevMode
    dependsOn compileJava
    dependsOn project(':ui:app').tasks.getByName("compileJava")
    dependsOn project(':ui:app2').tasks.getByName("compileJava")

    main = 'com.google.gwt.dev.DevMode'


    classpath project(":ui:app2").configurations.gwtSdk

    // Java sources first, so that changes get picked up on refresh
    def sourceProjects = [":ui:app", ":ui:app2", ":i18n", ":clients:gwtrest", ":tools:json", ":model"];
    for(sourceProject in sourceProjects) {
        classpath project(sourceProject).sourceSets.main.java.srcDirs
        classpath project(sourceProject).sourceSets.main.resources.srcDirs
    }

    classpath project(':ui:app').sourceSets.main.runtimeClasspath
    classpath project(':ui:app2').sourceSets.main.runtimeClasspath

    // APT Generated sources
    classpath project(':ui:app').sourceSets.main.output.generatedSourcesDir

    for(sourceProject in sourceProjects) {
        classpath project(sourceProject).sourceSets.main.runtimeClasspath
    }


    // Server classes
    classpath sourceSets.main.runtimeClasspath

    args '-logLevel', 'WARN'
    args '-server', 'com.google.appengine.tools.development.gwt.AppEngineLauncher'
    args '-war', "${buildDir}/explodedDevMode"
    args '-startupUrl', 'login'
    args '-port', devServerPort
    args 'org.activityinfo.ui.ActivityInfoDevMode'
    args 'org.activityinfo.ui.AppDev'

    doFirst {
        // The SDK root is only available after appengineDownloadSdk runs
        def sdkRoot = System.getProperty('appengine.sdk.root')
        classpath "${sdkRoot}/lib/appengine-tools-api.jar"

        // The appengine agent is a runtime agent that makes sure
        // we don't use any classes that are forbidden in the AppEngine environment.
        // However, it doesn't seem to have been updated for the new Java8 runtime.
        //
        // We can't remove the agent entirely, because the AppEngineLauncher class
        // will throw an error if it is not on the classpath. So, as a workaround,
        // place it on the classpath, but don't install it as an agent.

        classpath "${sdkRoot}/lib/agent/appengine-agent.jar"

        // Write the application configuration pointing to the development database
        writeConfiguration mysql.localDev
        jvmArgs "-Dactivityinfo.config=${configFile}"
        jvmArgs "-Xdebug"
        jvmArgs "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"

        for(File classpathEntry : classpath) {
            logger.lifecycle("Classpath: " + classpathEntry)
        }

    }
}
```

**Comment by loosebazooka** [comment]
Oh, okay, looks like you just want to find the jars.

I think what you want to do is configure it something like this (if you're using this plugin - `com.google.cloud.tools.appengine-standard`), you explicitly point to the google cloud sdk (for now at least, we're working on making this downloadable).

....I haven't really tested this, but let me know if you think this could work.

```gradle
appengine {
  tools {
     cloudSdkHome = "path/to/your/cloudSdk" // or System.getProperty("cloud.sdk.root")
  }
}
```
The cloud sdk actually contains a lot of the jars you're looking for, I'm not sure what guarantee they are providing for those jars, but we use them.
They can be found in `"cloudSdkHome"/platform/google_appengine/google/appengine/tools/java/lib`, so you should be able to reference them relative to the cloudSdkHome you defined.

```gradle
task appengineDevMode(type: JavaExec) {
  ...
  doFirst {
      def appengineJavaLibs = "${project.appengine.tools.cloudSdkHome}/platform/google_appengine/google/appengine/tools/java"
      classpath "${sdkRoot}/lib/appengine-tools-api.jar"
      classpath "${sdkRoot}/lib/agent/appengine-agent.jar"
  }
}
```

**Comment by akbertram** [comment]
Ah yes, ok, this make sense.
So gcloud just uses the same java-sdk under the hood for the dev mode?
I see that I can get this sdk home by running `gcloud --format=json info`, so we could get this path at runtime without having to hard code it.

Just one question about starting the dev server for the java8 standard environment: is the agent still needed? Is it up to date? When I use version 1.9.59 of the java-sdk, the agent flags java.util.Optional as a restricted class.

**Comment by loosebazooka** [comment]
Are you still experiencing issues with Optional? We're probably going to need to follow up with the appengine devserver team.
