### ISSUE TITLE
No Support For Enhancer DataNucleus

### ISSUE THREAD

**Issue by Sanjay007** [GoogleCloudPlatform/app-gradle-plugin#238]

**Comment by loosebazooka** [comment]
This is as intended, it will not be supported in this plugin.

It is generally not recommended that appengine developers use datanucleus : https://cloud.google.com/appengine/docs/standard/java/datastore/jdo/overview-dn2

However, you can manually configure it if you chose to do so - something like this : https://stackoverflow.com/questions/29279503/how-can-i-run-datanucleus-enhancer-from-gradle
