### ISSUE TITLE
How to use this plugin for Functional/Integration tests

### ISSUE THREAD

**Issue by yuri-sergiichuk** [GoogleCloudPlatform/app-gradle-plugin#260]
Hello guys!

Could you please tell if there is any way to use the current plugin for integration (functional) tests?

In the previous [plugin](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin), there was a special task `appengineFunctionalTest`. Are there any ways to run the local dev server before my tests start and stop it after they are finished?

**Comment by yuri-sergiichuk** [comment]
@loosebazooka thanks for your response.

It's what I've already tried to do, but here's what I have in response from the plugin:
```
* What went wrong:
Execution failed for task ':main:webapp:appengineStart'.
> com.google.cloud.tools.appengine.cloudsdk.internal.process.ProcessRunnerException: Timed out waiting for the success message: '.*(Dev App Server is now running|INFO:oejs\.Server:main: Started).*'
```

I have some time-consuming functionality on the app startup, so it may take up to a 40 seconds to start the app, could it be the problem?

Before it fails, I do see some logging messages about starting the context initialization, and logs from my own app.

**Comment by TadCordle** [comment]
The `run` configuration has a `startSuccessTimeout` parameter you should be able to use to specify max Dev App Server wait time.

```
appengine {
  run {
    // Timeout after 60 seconds
    startSuccessTimeout = 60
  }
}
```

**Comment by yuri-sergiichuk** [comment]
@TadCordle thanks! that is what I needed.

Now I only need to figure out how to start and stop datastore emulator on the fly :-)

**Comment by JoeWang1127** [comment]
close as not planned
