### ISSUE TITLE
Plugins complains that Java App Engine components are not installed - but they are

### ISSUE THREAD

**Issue by StefMa** [GoogleCloudPlatform/app-gradle-plugin#266]
Currently I do a Udacity course where I have to checkout [this repository](https://github.com/udacity/ud867/tree/master/FinalProject).

I've never worked with *this* plugin - but with the gcloud in general - but in the "instruction"  they said simply:
```
Before going ahead you will need to be able to run a local instance of the GCE server. In order to do that you will have to install the Cloud SDK:
https://cloud.google.com/sdk/docs/

Once installed, you will need to follow the instructions in the Setup Cloud SDK section at:
https://cloud.google.com/endpoints/docs/frameworks/java/migrating-android

Note: You do not need to follow the rest of steps in the migration guide, only the Setup Cloud SDK.
```
Means I've done the following (gcloud was already installed):
*  gcloud auth application-default login
* gcloud components install app-engine-java

After that I wanted to execute `appengineStart` which complains with:
> Execution failed for task ':backend:appengineStart'.
> Validation Error: Java App Engine components not installed. Fix by running 'gcloud components install app-engine-java' on command-line.

So I tied to install the components again with `gcloud components install app-engine-java`. But glcoud reports just:
> All components are up to date.

Reinstalling doesn't help either.

After a quick lock into the code I found this line of code in the `appengine-plugins-core` plugin the this method `CloudSdk#validateAppEngineJavaComponents`.
They do something like that:
```
if (!Files.isDirectory(getAppEngineSdkForJavaPath())) {
      throw new AppEngineJavaComponentsNotInstalledException(
          "Validation Error: Java App Engine components not installed."
              + " Fix by running 'gcloud components install app-engine-java' on command-line.");
    }
```
The `getAppEngineSdkForJavaPath` returns this path:
> platform/google_appengine/google/appengine/tools/java/lib

I looked over at my $GCLOUD_LOCATION/platform... and found the lib directory. It is there.

After two hours of debugging I found out that my `~/.bash_profile` has this section:
`export GOOGLE_CLOUD_SDK_HOME=/Users/stefan/Developer/GoogleCloudSdk/bin`
I've quickly changed that to 
`export GOOGLE_CLOUD_SDK_HOME=/Users/stefan/Developer/GoogleCloudSdk/`
(notice that I've remove the `/bin`)

I don't know what I expect know 😅 but this should be somehow documented our the exception should be report it better. Maybe saying that the `GOOGLE_CLOUD_SDK_HOME` should point to your "HOME GCloudDir"....

**Comment by loosebazooka** [comment]
That's strange. Do you know what set GOOGLE_CLOUD_SDK_HOME to that path initially? It's just an env var that we read if the user sets it.

I guess the exception could output the directory we're looking for.

**Comment by StefMa** [comment]
I've installed the SDK long long time ago.
But as I remember correctly I have set this env var manually 🤔.

I think that would be a solution yes. But better would be saying something
like "Either the java-components arent installed OR the env var
GOOGLE_CLOUD_SDK_HOME
does not point to directory XXXX"

Am Di., 5. Juni 2018 um 21:28 Uhr schrieb Appu <notifications@github.com>:

**Comment by benjaminpmeier** [comment]
Also having this issue but exporting GOOGLE_CLOUD_SDK_HOME to my installation (~/google-cloud-sdk) did not resolve the problem.

**Comment by riyaza15** [comment]
Sam problem I get Please 
* What went wrong:
Execution failed for task ':backend:appengineStart'.
> Validation Error: Java App Engine components not installed. Fix by running 'gcloud components install app-engine-java' on command-line.
My Error message
Is there anybody to help me??

**Comment by loosebazooka** [comment]
Can you provide a few more details about your cloud sdk configuration and your grade config?

**Comment by Vkadel** [comment]
I'm working on the same repo for udacity. I cannot install the app-engine-java. This is what I get when I type: gcloud components install app-engine-java

Restarting command:
  $ gcloud components install app-engine-java

Can someone tell me what I'm doing wrong please?

**Comment by loosebazooka** [comment]
@vilasj @markpell ?

**Comment by Vkadel** [comment]
I can see that the temps where the components are getting downloaded are being generated, however the installer does not continue.

**Comment by swaroop05** [comment]
@StefMa @riyaza15 - Did you find any workaround to fix this issue.

**Comment by vilasj** [comment]
@Vkadel can you provide more information about your gcloud installation (run gcloud info), and also the full log of what happens when you run 'gcloud components install app-engine-java' (please remove any PII)? Thanks.

**Comment by Anuradha677** [comment]
> I can see that the temps where the components are getting downloaded are being generated, however the installer does not continue.

is your issue resolved? I am also facing same issue. If so, please help me on this.

**Comment by Anuradha677** [comment]
Issue resolved by running SDK as administartor.

**Comment by chanseokoh** [comment]
@Vkadel for your issue, if you are on Windows, running `gcloud components install` as an administrator may work: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/393#issuecomment-514066472

**Comment by Tiam-Abderezai** [comment]
I solved this issue by adding in build.gradle(:backend) the following script-block:

`appengine {`
    `tools{`
     `   cloudSdkHome= "C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk"`
    `  }`
`}`

Note:
- Since this problem is with Windows 10, you MUST add " \\\ " or double back-slash instead of \ or /.
- I used the exact PATH in the system's Environment Variable after GoogleCloudSDK installation, and pasted in the block.

**Comment by chanseokoh** [comment]
@Tiam-Abderezai note that your workaround makes the plugin to stop using the auto-managed Cloud SDK (by default installed at [`%LOCALAPPDATA%/google/ct4j-cloud-sdk/LATEST/google-cloud-sdk` on Windows](https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/USER_GUIDE.md#configuration)). Since you're designating your own Cloud SDK, you may need to manually upgrade your Cloud SDK from time to time.

**Comment by Tiam-Abderezai** [comment]
@chanseokoh Ok thanks for letting me know. I will keep a reminder to reference this in the future. I tried setting it up the way you mentioned, but unfortunately I ran to the same issue again. This is for a Udacity project, so for now it's not important, but I will keep that in mind and reference this in the future when I work on more important projects.

**Comment by cloudoceansoft** [comment]
In my windows 7 machine it is not working even though ran as an administrator.
Please help

**Comment by JoeWang1127** [comment]
close as not planned
