### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by DevJoseWeb** [GoogleCloudPlatform/app-gradle-plugin#278]
FAILURE: Build failed with an exception.
* Where:
Build file '/home/web2ajax/SIMPLUS/build.gradle' line: 17
* What went wrong:
A problem occurred evaluating root project 'gestao'.
> Failed to apply plugin [id 'org.springframework.boot']
   > Spring Boot plugin requires Gradle 4.0 or later. The current version is Gradle 2.12
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 6.947 secs
web2ajax@cloudshell:~/SIMPLUS (simplus-api)$

**Comment by loosebazooka** [comment]
@DevJoseWeb, I'm going to close this. Please open a new issue if you find anything directly related to the appengine plugin.
