### ISSUE TITLE
Using Gradle 4.x's implementation configuration results in runtime exceptions

### ISSUE THREAD

**Issue by TWiStErRob** [GoogleCloudPlatform/app-gradle-plugin#290]
I set up the project using the sample project and using the latest Gradle (4.9):
https://docs.gradle.org/4.9/userguide/java_plugin.html#sec:java_plugin_and_dependency_management

`compile` is deprecated since 4.0, but this plugin still relies on it and doesn't work if using the new replacement configuration `implementation`. The server started up with `jettyRun` but when I tried to do any operations on it it crashed with `ClassNotFoundException`s. After changing all my `implementation`s to `compile` it started working.

Note: `providedCompile` should also be the new `compileOnly` configuration.

Since the Gradle requirements are "2.0.0 + | 4.0 or newer", it should support this feature.

**Comment by loosebazooka** [comment]
`jettyRun` is not part of the appengine plugin. So I can't sure this is an issue with appengine plugin in particular. From my preliminary search of our code, we don't explicitly reference "compile" dependencies anywhere. Can you provide some more info on your error? Maybe the gradle output?

**Comment by TWiStErRob** [comment]
Huh, good point; I found `appengineRun` few hours after I opened this. I tried now with `appengineRun` + `implementation` and it indeed works.

Looks like originally I found one of the locations where the documentation suggests `jettyRun` and ran with that: https://cloud.google.com/appengine/docs/flexible/java/using-gradle#testing_your_application_with_the_development_server
Must've entered a Google query where the flexible docs ranked higher than the standard docs.

Note: there are 3 instances: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fcloud.google.com%2Fappengine+"jettyRun"

**Comment by TWiStErRob** [comment]
(Note: I'm migrating from AppEngine 1.8.11 with Eclipse plugin to latest with Gradle due to Java 7 deprecation; back then there was no standard/flexible as far as I remember)

**Comment by loosebazooka** [comment]
Jetty run is how you would run flex applications (since they do not run on the standard appengine runtime)

**Comment by TWiStErRob** [comment]
So then this issue is still valid, isn't it? Just because one moves from standard to flex they shouldn't need to re-wire the whole Gradle dependency setup, right?

> jettyRun is not part of the appengine plugin
Is there a better place to report this?

**Comment by loosebazooka** [comment]
Hrmm. Your right. Looking around. Both the official Gradle and the gretty plugin are deprecated/unmaintained. We might need to remove the reference from our docs and have users run Jetty directly.

**Comment by loosebazooka** [comment]
@parkjam4?

**Comment by parkjam4** [comment]
Yeah, we can take care of that.

**Comment by loosebazooka** [comment]
@parkjam4 looks like gretty is being maintined in a new repository
github.com/gretty-gradle-plugin, I'm going to see if that plugin works with gradle 4.x
