### ISSUE TITLE
Change of Project to projectId required version as required config

### ISSUE THREAD

**Issue by malkiatrandhawa** [GoogleCloudPlatform/app-gradle-plugin#291]
With recent release of version 2.0.0-rc3 for `app-gradle-plugin` 
logged changes is: Changed appengine.deploy.project -> appengine.deploy.projectId (#286)
It means i need to change to
deploy {
             projectId = "{app_name}"
    }
but by updating project to projectId i met with error 
```
> Deployment version must be defined or configured to read from system state
  1. Set appengine.deploy.version = 'my-version'
  2. Set appengine.deploy.version = 'APPENGINE_CONFIG' to use <version> from appengine-web.xml
  3. Set appengine.deploy.version = 'GCLOUD_CONFIG' to have gcloud generate a version for you.
```

Until  2.0.0-rc2 i was not defining version in deploy config and even as per google documentation 
```
version | The version of the app that will be created or replaced by this deployment. If you do not specify a version, one will be generated for you.
-- | --
```
Is version mandatory with new change and not autogenerated anymore?

**Comment by loosebazooka** [comment]
You can still autogenerate by using GCLOUD_CONFIG. Version 2.0.0 onward will require you set both values (project and version).
```
  3. Set appengine.deploy.version = 'GCLOUD_CONFIG' to have gcloud generate a version for you.
```
This will have the same effect has not defining verison in previous versions.

**Comment by malkiatrandhawa** [comment]
Awesome, thanks for quick response.
