### ISSUE TITLE
<static-files> configuration has no effect

### ISSUE THREAD

**Issue by kriim** [GoogleCloudPlatform/app-gradle-plugin#293]
It seems that the plugin ignores the `<static-files>` section in the `appengine-web.xml`.

I created a HTML file at `src/main/webapp/WEB-INF/index.html`.

Content of `appengine-web.xml`:

    // Other settings ...

    <static-files>
      <include path="/index.html" />
    </static-files>

Content of `web.xml` (I tried this with and without the `welcome-file-list` element):

    <welcome-file-list>
      <welcome-file>index.html</welcome-file>
    </welcome-file-list>

When visiting `localhost:8000` or `localhost:8000/index.html` no file is found and the development server responds with a 404 error code:

    com.google.appengine.tools.development.jetty9.LocalResourceFileServlet doGet
    WARNING: No file found for: /index.html

These are the contents of the generated `app.yml` when running `appengineStage` (not sure if this is relevant):

    runtime: java8
    inbound_services:
      - warmup
    derived_file_type:
      - java_precompiled
    threadsafe: True
    auto_id_policy: default
    api_version: '1.0'
    handlers:
      - url: (/.*)
        static_files: __static__\1
        upload: __NOT_USED__
        require_matching_file: True
        login: optional
        secure: optional
      - url: /
        script: unused
        login: optional
        secure: optional
      - url: /.*/
        script: unused
        login: optional
        secure: optional
      - url: /_ah/.*
        script: unused
        login: optional
        secure: optional

    skip_files: app.yaml

app-gradle-plugin: 2.0.0-rc3
GCloud SDK: 215.0.0 (also tested with 218.0.0)
Dev App Server version: 1 (I didn't change the default setting of the plugin in version 2.0.0-rc3)

**Comment by loosebazooka** [comment]
Your index.html needs to be in `webapp` not `webapp/WEB-INF` for this to work.

**Comment by kriim** [comment]
Oh ok, thanks.

It works as expected now.
