### ISSUE TITLE
Set an env variable to track server-side usage of gcloud

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/app-gradle-plugin#3]
I am assuming here that our Gradle plugin will use `gcloud` (i.e., no API calls) for every task.

We need to set the following env variable before calling gcloud to track server-side usage coming from this plugin.

`CLOUDSDK_METRICS_ENVIRONMENT`

A unique string that can identify our new Gradle plugin will do. For example, our IntelliJ plugin uses `gcloud-intellij` as in [here](https://github.com/GoogleCloudPlatform/gcloud-intellij/issues/542).

This issue is just as a heads-up. Nothing urgent.

**Comment by loosebazooka** [comment]
done!
