### ISSUE TITLE
ERROR: (gcloud.beta.app.deploy) Error Response: [2] Cloud Container build succeeded but returned an empty result.

### ISSUE THREAD

**Issue by fschirl** [GoogleCloudPlatform/app-gradle-plugin#302]
I tried to deploy a new version where just 1 file was changed. I constantly getting this error using:
gcloud beta app deploy --no-promote --project=XXXXX
same with
gcloud beta app deploy --project=XXXXX

**Comment by loosebazooka** [comment]
If this is still an issue please re-open. However it appears you are using gcloud directly and might benefit from contacting them: https://cloud.google.com/sdk/docs/getting-support.
