### ISSUE TITLE
v2.0.0 non-RC?

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/app-gradle-plugin#303]
Is there any release planned? It has been some time since rc-3 now and it still gives continues warnings.

`WARNING: You are a using release candidate 2.0.0-rc3. Behavior of this plugin has changed since 1.3.5. Please see release notes at: https://github.com/GoogleCloudPlatform/app-gradle-plugin.
Missing a feature? Can't get it to work?, please file a bug at: https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues.`

**Comment by loosebazooka** [comment]
Yeah sorry this has been going on a comically long time. Our planned release for `2.0.0` is next if we receive no issues with `2.0.0-rc6`

**Comment by chanseokoh** [comment]
2.1.0 is the most recent as of now. Closing.
