### ISSUE TITLE
Is managed SDK still working ? 

### ISSUE THREAD

**Issue by martinbonnin** [GoogleCloudPlatform/app-gradle-plugin#304]
I just setup the plugin on a linux host and got this exception:

    Validation Error: SDK location '/home/martin/.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk' is not a directory.

After some investigations, it turns out that it works well if I force the cloud-sdk-home in `appengine.tools.cloudSdkHome`.

I am still confused because the [documentation](https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/50c021e72b7cee21738529e72265bd355992b692/USER_GUIDE.md#L29) says that CloudSDK needs to be downloaded before running the plugin but the plugin contains a [tasks to download it as well](https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/479c9be0a7676d8908816eeda4c97b3ebd31ea7b/src/main/java/com/google/cloud/tools/gradle/appengine/core/AppEngineCorePluginConfiguration.java#L45). 

Can you clarify how to setup the plugin ?

**Comment by loosebazooka** [comment]
Can you show me your config? (build.gralde)

**Comment by martinbonnin** [comment]
Config below. It's working now. To clarify, my issue is that it took me a couple of hours this morning to figure this stuff out. At some point I wanted to make a PR to tell users to define their `appengine.tools.cloudSdkHome` but then I saw there is all this managed SDK code so maybe there's a way to have the setup working without ?

    buildscript {
        ext.kotlin_version = '1.2.71'
        repositories {
            jcenter()
            mavenCentral()
        }
        dependencies {
            classpath 'com.google.cloud.tools:appengine-gradle-plugin:2.0.0-rc3'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        }
    }
    
    repositories {
        maven {
            url 'https://maven-central.storage.googleapis.com'
        }
        jcenter()
        mavenCentral()
    }
    
    apply plugin: 'kotlin'
    apply plugin: 'war'
    apply plugin: 'com.google.cloud.tools.appengine-standard'
    
    dependencies {
        providedCompile group: 'javax.servlet', name: 'javax.servlet-api', version: '3.1.0'
        compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
        compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
        compile 'com.google.cloud:google-cloud-datastore:1.14.0'
        compile 'com.squareup.moshi:moshi:1.5.0'
        compile 'com.squareup.moshi:moshi-kotlin:1.5.0'
    }
    
    appengine {
        tools {
            cloudSdkHome = "/home/martin/google-cloud-sdk"
        }
        deploy {
            projectId = 'GCLOUD_CONFIG'
            version = 'GCLOUD_CONFIG'
            stopPreviousVersion = true
            promote = true
        }
    }

**Comment by loosebazooka** [comment]
Yeah the managed sdk code is for auto downloading. So if you don't point to a cloud sdk it should download one. I'm not sure exactly why you were getting that validation error (I'm not near a computer), but it could be that some file exists in that location?

**Comment by martinbonnin** [comment]
Then the README.md is misleading because it states Cloud SDK as a dependancy:

    The Cloud SDK is required for this plugin to function. Download and install it before running any tasks.

There's no `/home/martin/.cache/google-cloud-tools-java` so if I remove the hardcoded cloudSdkHome, nothing gets downloaded.

**Comment by martinbonnin** [comment]
But even if it auto-downloads, there are still manual steps needed to authenticate, right ? Something like `gcloud init` ? Or are you able to make this interactive ?

**Comment by loosebazooka** [comment]
Yeah it's an example, but an image could potentially already have the sdk already on it.

**Comment by JoeWang1127** [comment]
close as not planned

**Comment by martinbonnin** [comment]
@JoeWang1127 I guess this is just a wording issue. The [current doc](https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/16620c59dcfffa074a20c39e2a1e9027d114672f/USER_GUIDE.md) says:

```
The [Cloud SDK](https://cloud.google.com/sdk) is required for this plugin to function.
 Versions greater than 2.0.0 will automatically download and install it for you. You may 
also choose to download and install it before running any tasks.
```

I think the current behaviour is this:

```
The plugin requires the [gcloud](https://cloud.google.com/sdk) CLI. If `gcloud` 
if found in your PATH, it will be used. Else the plugin will download and install 
`gcloud` automatically. 
```

Is that an appropriate depiction of the current state? If yes, I can make a PR.

**Comment by chanseokoh** [comment]
I think the current behavior ignores `PATH`?

**Comment by elefeint** [comment]
Reopening because this is indeed confusing. [This section](https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/16620c59dcfffa074a20c39e2a1e9027d114672f/USER_GUIDE.md#tools) describes the behavior well, but "The Cloud SDK is required for this plugin to function. Download and install it before running any tasks." sentence is ambiguous.


We'll accept the documentation contribution -- it can point to the table describing `cloudSdkHome`/`cloudSdkVersion`, or say something along the lines of "Cloud CLI will be downloaded automatically, unless `cloudSdkHome` property is provided.

**Comment by martinbonnin** [comment]
Pull request there: https://github.com/GoogleCloudPlatform/app-gradle-plugin/pull/434

**Comment by mpeddada1** [comment]
Closing this issue given the clarification in the documentation (#434). Please feel free to reopen if there are any further questions.
