### ISSUE TITLE
Warning on task property validation when building

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/app-gradle-plugin#318]
What's this? Should this be taken care of?

```
$ ./gradlew clean build
...
>  Task :validateTaskProperties
Task property validation finished with warnings:
  - Warning: Task type 'com.google.cloud.tools.gradle.appengine.appyaml.StageAppYamlTask': property 'stagingExtension.extraFilesDirectories' is not annotated with an input or output annotation.
  - Warning: Task type 'com.google.cloud.tools.gradle.appengine.standard.StageStandardTask': property 'stageStandardExtension.dockerfile' has @Input annotation used on property of type java.io.File.
```

**Comment by loosebazooka** [comment]
Yeah, I think dockerfile needs to be updated to be `@InputFile`, however I'm not sure how to handle the `extraFilesDirectories` parameter, maybe there's a way to specify that it is handled by another method? I'll look around

**Comment by TadCordle** [comment]
I think we do something similar with Jib? Something like having two getters, one that returns a `String` and has the `@Input` annotation, and one that returns a `Path` (or `File` in this case) that has `@Internal`. Maybe adding `@InputFile` to the internal one would work?

**Comment by loosebazooka** [comment]
Trying out @TadCordle's solution
