### ISSUE TITLE
Usage when offline

### ISSUE THREAD

**Issue by anbuck** [GoogleCloudPlatform/app-gradle-plugin#335]
I would like to be able to compile my project that uses the app-gradle-plugin when I am not connected to the internet, but when I try to do so, I get a ManagedSdkVerificationException. It seems that the plugin blows up when it is checking whether it is up to date. Instead it should simply skip that check.

**Comment by anbuck** [comment]
And the same rule should apply if the computer is connected to the internet, but is unable to connect to the server to check what the latest version of the plugin is. The server going down should not block me from building my project.

**Comment by loosebazooka** [comment]
We've been working under the assumption than `LATEST` means we *will* update as necessary. However this is an interesting question, and maybe we can ignore failures.

If you do want to manually control updates without using the managed SDK you can use an environment var to point to the cloud sdk installation which can be more portable than hardcoding it in.

```
appengine {
  tools {
    cloudSdkHome = System.getenv("CLOUD_SDK_HOME")
  }
}
```

**Comment by anbuck** [comment]
LATEST should mean that if a newer version of the SDK is detected, it should be downloaded, but why would a failure to connect to the server block the build? That would mean if I want the SDK version to be updated automatically, I can never do work on airplanes? What is the advantage of failing in this case?
