### ISSUE TITLE
Can't use project variable in project definition

### ISSUE THREAD

**Issue by glaforge** [GoogleCloudPlatform/app-gradle-plugin#353]
https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/7801515f7f7e1f895552f770efac77ee94c13510/src/main/java/com/google/cloud/tools/gradle/appengine/core/DeployExtension.java#L140

Because of this line to suggest users to upgrade their gradle build to use `projectId` instead of `project`, it's impossible to do the following:

```
appengine {
    stage.artifact = "${buildDir}/libs/${project.name}-${project.version}-all.jar"
    deploy {
        projectId = project.name
        version = project.version.replaceAll('.', '_')
    }
}
```

In `stage.artifact` I can use `${project.name}` without a problem.
But in the `deploy` section, I can't use Gradle's `project` variable because you override the `getProject()` method.

**Comment by JoeWang1127** [comment]
close as not planned. Please re-open if it's still relevant.
