### ISSUE TITLE
Add a delay to promote

### ISSUE THREAD

**Issue by Sdwz** [GoogleCloudPlatform/app-gradle-plugin#363]
Hi,

I would like to make a suggestion. Would it be a good idea to add a delay to promote a new version when we deploy with promote set to true ?

My use case is as follow : 

- AppEngine standard java 8
- Deploy configuration 
`	deploy {
		version = projectVersion
		projectId = gcpProjectId
		promote = "true"
	}`
- Instance setup in dev : 
`min_idle_instances: 0
min_instances: 0
max_instances: 2`

When I'm deploying, service becomes unavailable because promotion happens and warmup takes  ~~64sec. A delay would allow me to promote automatically after an estimated warmup delay, and avoid service disruption.

Thanks.

Cheers

**Comment by loosebazooka** [comment]
Unfortunately we cannot do this in the plug-in. Promotion happens directly in gcloud.

@vilasj is this something that gcloud could provide?

@saturnism do you have any idea what the right solution is here?

**Comment by saturnism** [comment]
@Sdwz have you configured a health check? I think adding one of the checks should help w/ traffic routing to only up and running instances. https://cloud.google.com/appengine/docs/standard/java/how-instances-are-managed

/cc @ludoch

**Comment by saturnism** [comment]
short of that, is to do a blue/green deployment, and then promoting the new version manually after the new version is verified up and running.

**Comment by JoeWang1127** [comment]
close as obsolete.
