### ISSUE TITLE
Running appengineDeploy Creates .gcloudignore File by Default

### ISSUE THREAD

**Issue by SudharakaP** [GoogleCloudPlatform/app-gradle-plugin#376]
I've noticed starting recently that running `./gradlew appengineDeploy` on a Gradle project creates the `.gcloudignore` file within the staging directory. I was wondering if this kinda behaviour was added recently? I had to run `gcloud config set gcloudignore/enabled false` before deploying since otherwise the `.gcloudignore` file seems to prevent files for deploying correctly. :thinking: 

Any help or thoughts on this will be greatly appreciated. :smile:

**Comment by loosebazooka** [comment]
oh interesting, I'm not sure what this is. Let me ask someone on the gcloud team.
@vilasj ?

**Comment by vilasj** [comment]
I am not aware of any recent changes to app deploy behavior. Here are the docs about .gcloudignore: https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore.

**Comment by SudharakaP** [comment]
Hmm, not sure how it happened. For now I'll close this issue as I couldn't recreate the issue a second time when I built the staging directory from scratch again. I'll let you know if I see this issue again with a reproducible example. Thanks a lot. :thinking:

**Comment by SudharakaP** [comment]
I've managed to recreate this issue. Also it was reported by a user at; https://github.com/jhipster/generator-jhipster/issues/11880

This only happens when running, `./mvnw package appengine:deploy` or `./gradlew appengineDeploy` commands. The staging directory is auto populated by a `.gcloudignore` file which seems to prevent all the files in the target directory from uploading correctly. If you would like a sample repository I can provide one too. :smile:

**Comment by chanseokoh** [comment]
> If you would like a sample repository I can provide one too.

We'd appreciate it!

**Comment by SudharakaP** [comment]
@chanseokoh : Here are the two repos. One using Maven and the other using Gradle; 

https://github.com/SudharakaP/jhipster-sample-gae and https://github.com/SudharakaP/jhispter-gae-sample-gradle

We use, `./mvnw package appengine:deploy -DskipTests -Pgae,prod,prod-gae` to deploy the Maven project and, `./gradlew appengineDeploy -Pgae -Pprod-gae` to deploy the Gradle one.  Let me know if you need any further information.

**Comment by chanseokoh** [comment]
In my testing, I do see that gcloud creates the file.
```
[INFO] GCLOUD: Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
```
However, it is uploading 1128 files, and it looks like it's working fine?
```
[INFO] Detected App Engine app.yaml based application.
Jun 02, 2020 1:01:01 PM com.google.cloud.tools.appengine.operations.GcloudRunner run
INFO: submitting command: /.../.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/gcloud app deploy --version 1 --project ...
[INFO] GCLOUD: Services to deploy:
[INFO] GCLOUD: 
[INFO] GCLOUD: descriptor:      [/=.../gitrepos/jhipster-sample-gae/target/appengine-staging/app.yaml]
[INFO] GCLOUD: source:          [.../gitrepos/jhipster-sample-gae/target/appengine-staging]
[INFO] GCLOUD: target project:  [....]
[INFO] GCLOUD: target service:  [default]
[INFO] GCLOUD: target version:  [1]
[INFO] GCLOUD: target url:      [https://....ue.r.appspot.com]
[INFO] GCLOUD: 
[INFO] GCLOUD: 
[INFO] GCLOUD: Beginning deployment of service [default]...
[INFO] GCLOUD: Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
[INFO] GCLOUD: #============================================================#
[INFO] GCLOUD: #= Uploading 1128 files to Google Cloud Storage             =#
```

I've gone through jhipster/generator-jhipster#11880. The content of the `.gcloudignore` file in https://github.com/jhipster/generator-jhipster/issues/11880#issuecomment-637231119 seems perfectly harmless, ignoring things like `.git` or `target/. Are you sure removing `.gcloudignore` resolves the issue? If it is indeed the case, how were you even able to figure out that `.gcloudignore` was actually causing a trouble?

**Comment by SudharakaP** [comment]
@chanseokoh : After deploying it did you try to go into the home page? Or look at the logs or deployed files. For myself it gives a 500 error and the deployed files section (within the logging section) is empty. 

Yes, running the `gcloud config set gcloudignore/enabled false` command before building made sure that the `.gcloudigore` is not generated and then it was working fine.

**Comment by chanseokoh** [comment]
Your application always seem to return 500. Perhaps it needs to connect to a SQL server at the following URL?

`jdbc:mysql://google/gaemaventest?cloudSqlInstance=innate-marking-279106:us-central1:appenginetest&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false`

Anyways, I think I know what went wrong. There's a directory named `build` under `repository/`, and gcloud is skipping the directory as specified in `.gcloudignore`.
```
[INFO] GCLOUD: --------------------------------------------------
[INFO] GCLOUD: Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
[INFO] GCLOUD: DEBUG: Skipping file [.gcloudignore]
[INFO] GCLOUD: DEBUG: Skipping file [repository/org/springframework/data/build]
[INFO] GCLOUD: INFO: Incremental upload skipped 0.0% of data
[INFO] GCLOUD: DEBUG: Uploading 1128 files to Google Cloud Storage
[INFO] GCLOUD: DEBUG: Using [16] threads
[INFO] GCLOUD: #============================================================#
[INFO] GCLOUD: #= Uploading 1128 files to Google Cloud Storage             =#
```

**Comment by chanseokoh** [comment]
A workaround would be to supply your own `.gcloudignore` so that gcloud doesn't auto-create a default one.

**Comment by SudharakaP** [comment]
> Your application always seem to return 500. Perhaps it needs to connect to a SQL server at the following URL?
> 
> `jdbc:mysql://google/gaemaventest?cloudSqlInstance=innate-marking-279106:us-central1:appenginetest&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false`

@chanseokoh : No the db is generated when we run `jhipster gae` which is what automatically generates the GAE configuration. Sorry I should have been more clearer. If you want me to deploy the application with the full db and stuff, I can do that too. 

> Anyways, I think I know what went wrong. There's a directory named `build` under `repository/`, and gcloud is skipping the directory as specified in `.gcloudignore`.

Ah got it. I didn't realize that's what was causing the issue. Interesting. Let me try that workaround; I think that should work. Thanks a lot. :smile: :smile:

**Comment by SudharakaP** [comment]
@chanseokoh : Yes that seems to work. Is this something you guys are gonna fix on your end? if so for now I can add this to the readme and let users know rather than generating a `.gcloudignore` file and also keep this issue open. :smile:

**Comment by chanseokoh** [comment]
Since it is very common for Java package names to include the name `build`, I filed an internal bug against Cloud SDK (b/158016853). @vilasj

I should close this issue though. It's an issue in Cloud SDK and unrelated to this repo. But I'll update here once it's fixed in Cloud SDK.

**Comment by SudharakaP** [comment]
@chanseokoh : Wonderful. Yes please do let me know when it's fixed so we could update it on our end. Thanks a lot for your help. Appreciated. :handshake:

**Comment by vilasj** [comment]
After further investigation, we have found that this change was introduced in version 292.0.0. As a workaround, while it is being fixed, you could revert/pin to 291.0.0 via gcloud components update --version=291.0.0 .

**Comment by chanseokoh** [comment]
@SudharakaP the internal bug is marked fixed; the default `.gcloudignore` will no longer have the `build/` entry. The next Cloud SDK may contain this fix (although I can't guarantee 100%). And of course, you cannot expect that your users are always using the latest Cloud SDK.

**Comment by SudharakaP** [comment]
@chanseokoh : Thanks for letting me know. I've already included [a line in our code](https://github.com/jhipster/generator-jhipster/pull/11887/files#diff-db6b3ff2520083c61a939019cc621219R776) to warn users about this. I will look into changing that line perhaps when the next Cloud SDK build is released.
