### ISSUE TITLE
App don`t start from index.jsp as it declared in web.xml <welcome-file-list> after deploy on GCloud

### ISSUE THREAD

**Issue by buzzgamesnews** [GoogleCloudPlatform/app-gradle-plugin#379]
**Problem you have encountered:**
- after deploy app to appengine on gcloud with gradle default web page is index.html. BUT in web.xml declared:
```
<welcome-file-list>
   <welcome-file>index.jsp</welcome-file>
</welcome-file-list>
```

in local environment (localhost:8080) it start from index.jsp as I expected and declared, but after deploy on prod environment is not

maybe plugin need configured with welcome page in build.gradle file ?

**Comment by loosebazooka** [comment]
interesting. maybe @ludoch has the answer?

**Comment by buzzgamesnews** [comment]
I really hope for it
