### ISSUE TITLE
appengineStart task stops writing output to the log file after Gradle quits

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-gradle-plugin#43]
Steps to reproduce:

1. gradle appengineStart
2. tail -f [path to log reported in console] 
3. open http://localhost:8080/

Notice that if you keep making HTTP requests to the app, the activity is not shown in the log.

**Comment by loosebazooka** [comment]
changed to write to gradle log

**Comment by meltsufin** [comment]
As part of which PR?

**Comment by loosebazooka** [comment]
oops
