### ISSUE TITLE
Question: What is the minimum supported Gradle version?

### ISSUE THREAD

**Issue by TWiStErRob** [GoogleCloudPlatform/app-gradle-plugin#450]
The repository sources are misleading:

https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/1d3084f175450d4a8188317092206737a4878e15/README.md?plain=1#L14

https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/1d3084f175450d4a8188317092206737a4878e15/src/main/java/com/google/cloud/tools/gradle/appengine/AppEnginePlugin.java#L37

https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/1d3084f175450d4a8188317092206737a4878e15/src/main/java/com/google/cloud/tools/gradle/appengine/core/AppEngineCorePluginConfiguration.java#L35

**Comment by emmileaf** [comment]
Thank you for catching this - I believe the README has the intended version compatibility here, and we likely missed updating `GRADLE_MIN_VERSION` used in the enforcement check and test suite. Will put in a PR for aligning them. (This may also need to be re-visited after #451, as you noted.)

**Comment by TWiStErRob** [comment]
@emmileaf thanks. Implementation-wise I would actually merge #451 first, and then move the constant to `GradleCompatibility` class so there's only one, not two of them.
