### ISSUE TITLE
Unable to stage app: 'posix:permissions' not supported as initial attribute on Win11 if project has *.jsp file.

### ISSUE THREAD

**Issue by buzzgamesnews** [GoogleCloudPlatform/app-gradle-plugin#458]
The error has been appearing since yesterday ( 06/28/2023 ) I did some research and realized that the error appears after the *.jsp module scans the appengineStage files:

_Beginning interaction for module default...
0% Scanning for jsp files.
0% Compiling jsp files.
Unable to stage app: 'posix:permissions' not supported as initial attribute_

After I tried to remove all *.jsp files and appengineStage was successful without errors, but *.jsp files are part of the project, what can I do ?
It doesn't matter what is in these files, the error appears even if you put an empty *.jsp file in the directory webapp.

**Comment by lqiu96** [comment]
Hi @buzzgamesnews, thanks for reporting this. I see you linked an issue to `appengine-java-standard`. It seems like this *should* be resolved with bumping guava's version. Let us know if you see otherwise.

**Comment by buzzgamesnews** [comment]
Thx
workaround -> [https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/458](https://www.google.com/url?q=https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/458&sa=D&source=buganizer&usg=AOvVaw1ORAD-iyIM90K1zmyCnIbg)
