### ISSUE TITLE
Complete plugin configuration settings should be documented 

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-gradle-plugin#59]
Whether it's hosted on Github or on our cloud docs site, a user should be able to find full reference docs from here.

**Comment by bodiam** [comment]
@patflynn I'm actually looking for the documentation. This plugin is currently giving me errors all over (for example, a missing src/main/appengine dir, which apparently is needed). I assume the plugin also wants something in the directory, but I have no idea what at the moment. Some documentation would be great.

**Comment by patflynn** [comment]
@loosebazooka 
@lesv

**Comment by lesv** [comment]
+1  -- I think you also moved the Dockerfile from appengine/ to Docker/ -- We need to doc that.

**Comment by lesv** [comment]
@bodiam 
appengine/
  app.yaml

Take a look at: https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/helloworld-servlet

**Comment by bodiam** [comment]
Thanks, I got a bit further in the meantime! Thanks for the link!

**Comment by loosebazooka** [comment]
There is a special task to see the whole configuration, if you'd like to see what the defaults are.

```
./gradlew appengineShowConfiguration
```

**Comment by patflynn** [comment]
Do we still have work to do here?

**Comment by v7r** [comment]
Don't see documentation for Data Nucleus class enhancer configuration, appengineShowConfiguration is not helping.

**Comment by patflynn** [comment]
@v7r datanuclueus is no longer supported by our plugins.  You can find instructions for configuring it with the datanucleus 3rd party build plugins here: https://cloud.google.com/appengine/docs/standard/java/datastore/jdo/overview-dn2
