### ISSUE TITLE
FR: Please require the test task before running plugin tasks

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-gradle-plugin#69]
`mvn appengine:run` will always run unit tests before running the app.
`gradle appengineRun` doesn't.

I'm trying to add the required lines to my build.gradle to do this, but it would be easier if we did it directly.

**Comment by lesv** [comment]
A work around is to add the following to your `build.gradle`:
```
// Always run unit tests
appengineRun.dependsOn test
appengineDeploy.dependsOn test
appengineStage.dependsOn test
```

**Comment by loosebazooka** [comment]
Since the user can configure it, we won't implement this. It seems pretty non standard for development servers.
