### ISSUE TITLE
Why maintaining 2 plugins?

### ISSUE THREAD

**Issue by renaudcerrato** [GoogleCloudPlatform/app-gradle-plugin#76]
Are you guys aware that there's already a Gradle plugin for app-engine somewhere in your walls?

https://github.com/GoogleCloudPlatform/gradle-appengine-plugin

Joking apart, why maintaining 2 separate plugins?

**Comment by mpoehler** [comment]
Same question is discussed here: https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/262
