### ISSUE TITLE
Any way to pass configurations from gradlew command line?

### ISSUE THREAD

**Issue by junghoahnsc** [GoogleCloudPlatform/app-gradle-plugin#81]
Hello,

I'm trying to use this plugin and my build.gradle has
```
 appengine {
    deploy {   // deploy configuration
        stopPreviousVersion = true  // default - stop the current version
        promote = true              // default - & make this the current version
        project = 'my-project'
    }
}
```

And I'd like to overwrite `project` with `gradlew` command line.
I tried like
```
./gradlew appengineDeploy -Pappengine.deploy.project=xxx
```
but it didn't work. I tried many variants, but I couldn't find a solution.

Thanks,

**Comment by patflynn** [comment]
@loosebazooka this should work right?

**Comment by loosebazooka** [comment]
There's no gradle mechanism to do this. You would have to do this on your own, just read the property you set on the command line into the right configuration parameter.
```
appengine {
  deploy {
    project = property('appengine.deploy.project')
  }
}
```
```
./gradlew appengineDeploy -Pappengine.deploy.project=my-project
```

**Comment by junghoahnsc** [comment]
Thanks, that's the way what I'm doing now.
