### ISSUE TITLE
Google Cloud SDK not found when running from IntelliJ IDEA

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/app-gradle-plugin#82]
Hi,
I'm getting the following error on Mac/Debian when running any appengine command from IntelliJ IDEA:

Google Cloud SDK path was not provided and could not be found in any known install locations.

When I use the terminal and run it via ./gradlw everything works

**Comment by patflynn** [comment]
My guess is this is due to environmental differences b/w the OSX WM and bash.

https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/267 may fix this.

In the mean-time I though you'll have to manually configure the cloud SDK location in the gradle plugin.

**Comment by loosebazooka** [comment]
Is this an issue with the gradle plugin or the intellij integration? Are you running the command from the gradle window in intellij or using the cloud tools for intellij plugin?

**Comment by Burtan** [comment]
I've just tried again under Debian with gcloud being available from the terminal. It does NOT run using the right gradle sidebar. It does run using a terminal command.

**Comment by patflynn** [comment]
@Burtan have you installed the Cloud SDK in a non-standard location?  You may have to configure the location manually using tools.cloudSdkHome.  I don't think the Cloud SDK exports itself to the path for windowing environments.

**Comment by Burtan** [comment]
I think there is no standard location on linux? The installer script registers gcloud at the exact location where you put the files. Configuring cloudSdkHome works, thats how I do it atm.

**Comment by loosebazooka** [comment]
It's possible this is fixed using the newest version of the plugin that does some symlink following to find the cloud sdk.

**Comment by Burtan** [comment]
I can confirm it.
