### ISSUE TITLE
Support for build variants similiar to Android

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/app-gradle-plugin#83]

**Comment by loosebazooka** [comment]
Can you be more specific, what exactly are you trying to customize?

**Comment by Burtan** [comment]
At the moment I have two flavours of one service. One flavour is the sandbox, the other one is the production environment. I have one class with constants which I comment out depending on which flavour I want to publish. The constants contain API information like URL and client IDs.

**Comment by loosebazooka** [comment]
This seems like something that can be solved by gradle and isn't appengine specific. Android has defined a convention for doing that for Android projects and within the IDE, but it doesn't make sense for us to provide such a strong suggestion to app engine developers.

A way to mimic that behavior would be to do it on your own. Perhaps by controlling the sourceset includes?

Something like (I don't know if this will actually work, but you could play around with it, there are probably other ways to do this too) : 
```java
sourceSets {
  main {
    java {
      if ( /*some condition for debug*/ ) {
        srcDirs "src/variants/debug/java"
      }
      else if ( /*some condition for prod*/) {
        srcDirs "src/variants/prod/java"
      }
    }
  }
}
```

And here `some condition` can be checking a system or gradle property or something like that.

```
./gradlew assemble -Pvariant=debug
```

It's really up to you.

**Comment by Burtan** [comment]
Thanks, I'll look into it.
