### ISSUE TITLE
mutli module documentation

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-gradle-plugin#87]
Add documentation for users transitioning from EAR projects

**Comment by simci-wendeldw** [comment]
Any progress on the documentation so far? #86 is not very specific in the details and keeps you clueless.

**Comment by loosebazooka** [comment]
@simci-wendeldw coming back to this. What exactly are you looking for? For multi-module, local run is documented here (in some primitive form) : https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/USER_GUIDE.md

For deploy, since deployments don't happen atomically, there isn't too much of a reason to try to emulate that. You can just deploy each one on it's own, or chain them together in your own gradle command.

**Comment by simci-wendeldw** [comment]
okay. I'm working with android studio. (intellij)

If I have two modules as follow, how do I tell that one is the default service and the other a sub?

backend/build/exploded-app
backend/build/staged-app
backend/src/main/java
backend/src/main/webapp
backend/src/main/webapp/WEB-INF
backend/src/main/webapp/WEB-INF/appengine-web.xml

**Comment by loosebazooka** [comment]
@simci-wendeldw I only see one module `backend` here?

**Comment by simci-wendeldw** [comment]
I figured it out. It is basically very simple. Create another module and add the <service>name</service> tag to appengine-web.xml. Follow with a deploy.
