### ISSUE TITLE
provide clearDatastore property for dev appserver runs

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-gradle-plugin#90]
blocked on https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/303

**Comment by lostpebble** [comment]
I see this is set for the next release. Is there any way for me to clear the datastore on the dev appserver now? Been searching but haven't found a way to start the dev appserver manually with the flags just so I can clear it out.

**Comment by patflynn** [comment]
I think this fix went out with the last release.  Can you verify that this
still isn't working?
