### ISSUE TITLE
double spaced dev app server logs on Windows 10

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-gradle-plugin#91]
Same issue as: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/127

FYI this doesn't happen in CT4IJ which uses the appengine-plugins-core so I'm assuming this is specific to the build tools.

**Comment by lostpebble** [comment]
Yep, confirming that everything is spaced out. Lots of scrolling trying to go through logs.

**Comment by meltsufin** [comment]
Please re-open if this is still an issue.
