### ISSUE TITLE
Need instructions on how to run a debug session

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-gradle-plugin#96]
Somewhere in the Gradle and Maven plugin docs should be instructions on how to configure a local run for debugging.

**Comment by patflynn** [comment]
@lesv we should have this in the cloud docs too.

**Comment by lesv** [comment]
Do we have instructions already, or do I need to generate something?

**Comment by loosebazooka** [comment]
I thought we were centralizing docs? Would we have this in both the github docs and cloud docs?

**Comment by patflynn** [comment]
I guess cloud docs.

**Comment by loosebazooka** [comment]
done!
